Reimplemented make check target.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -97,21 +97,33 @@ test_cluster_example_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_cluster_example_SOURCES			= \
 	src/test-cluster-example/cpp/cluster_ex.cpp
 
+test-cluster-example.log: test-cluster-example
+	./'$<' > $@
+
 test_dynamic_fsm_LDADD				= $(SYSTEMOC_LIBS)
 test_dynamic_fsm_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_dynamic_fsm_SOURCES			= \
 	src/test-dynamic-fsm/cpp/design-dynamic-fsm.cpp
+
+test-dynamic-fsm.log: test-dynamic-fsm
+	./'$<' 100 > $@
 
 test_event_LDADD				= $(SYSTEMOC_LIBS)
 test_event_DEPENDENCIES				= $(SYSTEMOC_DEPENDENCIES)
 test_event_SOURCES				= \
 	src/test-event/cpp/design-event.cpp
 
+test-event.log: test-event
+	./'$<' 100 > $@
+
 # More integration required! check and synthesis
 test_fir_LDADD					= $(SYSTEMOC_LIBS)
 test_fir_DEPENDENCIES				= $(SYSTEMOC_DEPENDENCIES)
 test_fir_SOURCES				= \
 	src/test-fir/cpp/design-fir.cpp
+
+test-fir.log: test-fir
+	./'$<' 100 > $@
 
 # Needed by all synthesis targets for sqr
 test-fir.cpp: $(test_fir_SOURCES)
@@ -133,11 +145,17 @@ test_fsm_and_composition_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_fsm_and_composition_SOURCES		= \
 	src/test-fsm-and-composition/cpp/design-and-comp.cpp
 
+test-fsm-and-composition.log: test-fsm-and-composition
+	./'$<' 100 > $@
+
 # More integration required! check
 test_fsm_and_composition_diss_falk_LDADD	= $(SYSTEMOC_LIBS)
 test_fsm_and_composition_diss_falk_DEPENDENCIES	= $(SYSTEMOC_DEPENDENCIES)
 test_fsm_and_composition_diss_falk_SOURCES	= \
 	src/test-fsm-and-composition-diss-falk/cpp/design-and-comp.cpp
+
+test-fsm-and-composition-diss-falk.log: test-fsm-and-composition-diss-falk
+	./'$<' 100 > $@
 
 # More integration required! check
 test_fsm_junction_state_LDADD			= $(SYSTEMOC_LIBS)
@@ -145,11 +163,17 @@ test_fsm_junction_state_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_fsm_junction_state_SOURCES			= \
 	src/test-fsm-junction-state/cpp/design-junction-state.cpp
 
+test-fsm-junction-state.log: test-fsm-junction-state
+	./'$<' 100 > $@
+
 # More integration required! check
 test_fsm_xor_composition_LDADD			= $(SYSTEMOC_LIBS)
 test_fsm_xor_composition_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_fsm_xor_composition_SOURCES		= \
 	src/test-fsm-xor-composition/cpp/design-xor-comp.cpp
+
+test-fsm-xor-composition.log: test-fsm-xor-composition
+	./'$<' 100 > $@
 
 # More integration required! check
 test_fsm_xor_composition_diss_falk_LDADD	= $(SYSTEMOC_LIBS)
@@ -157,31 +181,49 @@ test_fsm_xor_composition_diss_falk_DEPENDENCIES	= $(SYSTEMOC_DEPENDENCIES)
 test_fsm_xor_composition_diss_falk_SOURCES	= \
 	src/test-fsm-xor-composition-diss-falk/cpp/design-xor-comp.cpp
 
+test-fsm-xor-composition-diss-falk.log: test-fsm-xor-composition-diss-falk
+	./'$<' 100 > $@
+
 test_getValueAt_LDADD				= $(SYSTEMOC_LIBS)
 test_getValueAt_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_getValueAt_SOURCES				= \
 	src/test-getValueAt/cpp/design-getValueAt.cpp
+
+test-getValueAt.log: test-getValueAt
+	./'$<' 100 > $@
 
 test_periodic_LDADD				= $(SYSTEMOC_LIBS)
 test_periodic_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_periodic_SOURCES				= \
 	src/test-periodic/cpp/design-periodic.cpp
 
+test-periodic.log: test-periodic
+	./'$<' 100 > $@
+
 test_sdf_LDADD					= $(SYSTEMOC_LIBS)
 test_sdf_DEPENDENCIES				= $(SYSTEMOC_DEPENDENCIES)
 test_sdf_SOURCES				= \
 	src/test-sdf/cpp/design-sdf.cpp
+
+test-sdf.log: test-sdf
+	./'$<' 100 > $@
 
 test_select_LDADD				= $(SYSTEMOC_LIBS)
 test_select_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_select_SOURCES				= \
 	src/test-select/cpp/design-select.cpp
 
+test-select.log: test-select
+	./'$<' 100 > $@
+
 # More integration required! check and synthesis
 test_sqr_LDADD					= $(SYSTEMOC_LIBS)
 test_sqr_DEPENDENCIES				= $(SYSTEMOC_DEPENDENCIES)
 test_sqr_SOURCES				= \
 	src/test-sqr/cpp/design-sqr.cpp
+
+test-sqr.log: test-sqr
+	./'$<' 100 > $@
 
 # Needed by all synthesis targets for sqr
 test-sqr.cpp: $(test_sqr_SOURCES)
@@ -202,11 +244,17 @@ test_systemc_sqr_DEPENDENCIES			= $(SYSTEMC_DEPENDENCIES)
 test_systemc_sqr_SOURCES			= \
 	src/test-systemc-sqr/cpp/systemc-sqr.cpp
 
+test-systemc-sqr.log: test-systemc-sqr
+	./'$<' 100 > $@
+
 # More integration required! check and synthesis
 test_sqr_int_LDADD				= $(SYSTEMOC_LIBS)
 test_sqr_int_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_sqr_int_SOURCES				= \
 	src/test-sqr-int/cpp/design-sqr.cpp
+
+test-sqr-int.log: test-sqr-int
+	./'$<' 100 > $@
 
 # Needed by all synthesis targets for sqr-int
 test-sqr-int.cpp: $(test_sqr_int_SOURCES)
@@ -228,15 +276,24 @@ test_src_snk_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_SOURCES				= \
 	src/test-src-snk/cpp/design-src-snk.cpp
 
+test-src-snk.log: test-src-snk
+	./'$<' 100 > $@
+
 test_src_snk_hierarchy_LDADD			= $(SYSTEMOC_LIBS)
 test_src_snk_hierarchy_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_hierarchy_SOURCES			= \
 	src/test-src-snk-hierarchy/cpp/design-src-snk-hierarchy.cpp
 
+test-src-snk-hierarchy.log: test-src-snk-hierarchy
+	./'$<' 100 > $@
+
 test_src_snk_multicast_LDADD			= $(SYSTEMOC_LIBS)
 test_src_snk_multicast_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_multicast_SOURCES			= \
 	src/test-src-snk-multicast/cpp/design-src-snk-multicast.cpp
+
+test-src-snk-multicast.log: test-src-snk-multicast
+	./'$<' 100 > $@
 
 # More integration required! check
 test_src_snk_multiplex_LDADD			= $(SYSTEMOC_LIBS)
@@ -244,20 +301,32 @@ test_src_snk_multiplex_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_multiplex_SOURCES			= \
 	src/test-src-snk-multiplex/cpp/design-src-snk-multiplex.cpp
 
+test-src-snk-multiplex.log: test-src-snk-multiplex
+	./'$<' 1000 10 20 5 0 2 > $@
+
 test_src_snk_multireader_LDADD			= $(SYSTEMOC_LIBS)
 test_src_snk_multireader_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_multireader_SOURCES		= \
 	src/test-src-snk-multireader/cpp/design-src-snk-multireader.cpp
+
+test-src-snk-multireader.log: test-src-snk-multireader
+	./'$<' 100 > $@
 
 test_src_snk_multireader_sched_LDADD		= $(SYSTEMOC_LIBS)
 test_src_snk_multireader_sched_DEPENDENCIES	= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_multireader_sched_SOURCES		= \
 	src/test-src-snk-multireader-sched/cpp/design-src-snk-multireader-sched.cpp
 
+test-src-snk-multireader-sched.log: test-src-snk-multireader-sched
+	./'$<' 100 > $@
+
 test_src_snk_multiwriter_LDADD			= $(SYSTEMOC_LIBS)
 test_src_snk_multiwriter_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_multiwriter_SOURCES		= \
 	src/test-src-snk-multiwriter/cpp/design-src-snk-multiwriter.cpp
+
+test-src-snk-multiwriter.log: test-src-snk-multiwriter
+	./'$<' 100 > $@
 
 # More integration required! check
 test_src_snk_noconsume_LDADD			= $(SYSTEMOC_LIBS)
@@ -265,25 +334,55 @@ test_src_snk_noconsume_DEPENDENCIES		= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_noconsume_SOURCES			= \
 	src/test-src-snk-noconsume/cpp/design-src-snk-noconsume.cpp
 
+test-src-snk-noconsume.log: test-src-snk-noconsume
+	./'$<' 100 > $@
+
 test_src_snk_void_LDADD				= $(SYSTEMOC_LIBS)
 test_src_snk_void_DEPENDENCIES			= $(SYSTEMOC_DEPENDENCIES)
 test_src_snk_void_SOURCES			= \
 	src/test-src-snk-void/cpp/design-src-snk-void.cpp
+
+test-src-snk-void.log: test-src-snk-void
+	./'$<' 100 > $@
 
 test_systemc_blocking_cosim_LDADD		= $(SYSTEMOC_LIBS)
 test_systemc_blocking_cosim_DEPENDENCIES	= $(SYSTEMOC_DEPENDENCIES)
 test_systemc_blocking_cosim_SOURCES		= \
 	src/test-systemc-blocking-cosim/cpp/design-cosim-blocking.cpp
 
+test-systemc-blocking-cosim.log: test-systemc-blocking-cosim
+	./'$<' > $@
+
 test_systemc_nonblocking_cosim_LDADD		= $(SYSTEMOC_LIBS)
 test_systemc_nonblocking_cosim_DEPENDENCIES	= $(SYSTEMOC_DEPENDENCIES)
 test_systemc_nonblocking_cosim_SOURCES		= \
 	src/test-systemc-nonblocking-cosim/cpp/design-cosim-nonblocking.cpp
 
+test-systemc-nonblocking-cosim.log: test-systemc-nonblocking-cosim
+	./'$<' > $@
+
 clean-local:
 	for i in $(noinst_PROGRAMS); do \
-	  rm -f $${i}.cpp $${i}.smx; \
+	  rm -f $${i}.cpp $${i}.smx $${i}.log; \
 	done
+
+ALL_LOGS = $(addsuffix .log, $(noinst_PROGRAMS))
+
+.PHONY: logs
+logs: $(ALL_LOGS)
+check-am: $(ALL_LOGS)
+	@error=0; \
+        for log in $^; do \
+          case "$$log" in \
+	    test-*.log) \
+	      if ! diff -u $$log $(srcdir)/src/$${log%.log}/golden.log > /dev/null; then \
+		echo "Check for $$log failed!!!"; error=1; \
+		diff -u $$log $(srcdir)/src/$${log%.log}/golden.log; \
+	      fi; \
+	      ;; \
+ 	  esac; \
+	done; \
+	exit $$error
 
 # .PHONY is outside conditionals to make automake happy
 .PHONY: synth-sw synth-pthread synth
