- fixed autotest script for systemoc-jpeg-decoder
git-archimport-id: falk@cs.fau.de--2007-systemoc-intern/SystemC-Examples--mainline--0.6--patch-255

diff --git a/systemoc-jpeg-decoder/autotest-sh b/systemoc-jpeg-decoder/autotest-sh
--- a/systemoc-jpeg-decoder/autotest-sh
+++ b/systemoc-jpeg-decoder/autotest-sh
@@ -9,24 +9,61 @@
 
 #
 golden_logs_dir=$srcdir/testlogs
+stimuli_dir=$srcdir/test_data
 
 logoutfile=autotest.log
+err_log=stderr.log
+
+# testing stimuli
+# use semicolon to separate parameter sets
+stimuli="jpeg-demo/4motion_128.jpg 128 128 3;"
+stimuli+="jpeg-demo/scd-logo-32.jpg 32 32 3;"
+#stimuli+="another.jpeg width height compCount;"
 
 #
 test_bin=$builddir/simulation-jpeg
 
-# call binary
-$test_bin 100 > $logoutfile 2> /dev/null
+# set list seperator
+IFS=';'
 
-# make sure 'golden' logfile exist! i leave checks for clarity
-diff $logoutfile $golden_logs_dir/100iter.log > /dev/null
+for stimulus in $stimuli;
+do
+  # reset list seperator
+  IFS=' '
+  stimulus=( $(echo $stimulus) )
 
-if [ $? -gt 0 ]; then
-  echo "JPEG autotest: logfiles differ."
-  test_failed=1
-fi
+  data=${stimulus[0]}
+  w=${stimulus[1]}
+  h=${stimulus[2]}
+  c=${stimulus[3]}
 
-# remove test logfile
-rm -f $logoutfile
+  #golden logfile has the name of the binary as prefix
+  gold=$golden_logs_dir/$data.log
+
+  # call binary
+  $test_bin $stimuli_dir/$data $w $h $c > $logoutfile 2> $err_log
+
+  if [ $? -gt 0 ]; then # if binary crashes
+      echo " $data: systemoc-jpeg-decoder autotest failed: test crashed.";
+      cat $err_log;
+      test_failed=1;
+  fi
+
+  # make sure 'golden' logfile exist
+  if [ -f $gold ]; then
+
+      # compare output and log
+      diff $logoutfile $gold > /dev/null
+  
+      if [ $? -gt 0 ]; then
+          echo " $bin: Support autotest failed: logfiles differ."
+          test_failed=1
+      fi
+  fi
+
+  # remove test logfile
+  rm -f $logoutfile $err_log
+
+done
 
 [[ -z "$test_failed" ]]
